name: Submodules Sync
on:
  - workflow_dispatch
jobs:
  sync:
    name: Submodules Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Update content
        run: |
          git submodule update --remote --init cms-content
          git add .
          git commit -m "Release at `date +'%Y-%m-%d %H:%M:%S'`" || echo "No changes to commit"
          git push origin HEAD